version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      PORT: 3333
      DATABASE_URL: '${DB_PROTOCOL:-postgresql}://${DB_USER}:${DB_PASSWORD}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME}?schema=public'
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ..:/home/app
      - /home/app/node_modules
